### ISSUE TITLE
Checking filename in header

### ISSUE THREAD

**Issue by rmuslimov** [yevhen-m/flake8-fancy-header#3]
I think assumption you've made here is incorrect:
https://github.com/yevhen-m/flake8-fancy-header/blob/master/flake8_fancy_header/checker.py#L24

Path python started from have nothing to deal with name of the file it checks. For example, my checker runs from different directory. Can you just check that given path exist on given machine and stop. 
For example you have `fokker.hotels.sell` just check that relpath exist for give file. 
Other solution you can be search for first `setup.cfg` down in the path.

**Comment by rmuslimov** [comment]
Or correct me if I missing something.

**Comment by yevhen-m** [comment]
@rmuslimov you are absolutely right. This path resolution approach does not work if you don't run flake8 from the project's root. Btw, you run flake8 from inside emacs which does not have  project's root as its cwd, correct? If not, please tell me what's your usage pattern, just curious.

> Can you just check that given path exist on given machine and stop

That's definitely not an option here because I still need to validate python module's header. 

> Other solution you can be search for first setup.cfg down in the path.

I guess this is the way to fix your issue while preserving all the plugin's functionality.
